import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Aside, { AsideFooter, AsideHeader } from "./components/Aside";

const FancyForm: NextPage = () => {


    return (
        <>
            <Head>
                <title>Jannick Jungbluth</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <article className="grid grid-cols-3 ">
                <figure className="col-span-2">

                    <div className="relative w-64 fancy-form flex flex-col gap-6 mx-auto">

                        <div className="heading text-[#fccc4c] text-xl bg-black bg-opacity-50 backdrop-blur-sm">Please enter your name below:</div>

                        {/* FIRST NAME */}
                        <div className="input-box">
                            <input type="text" required />
                            <span>First Name</span>
                        </div>

                        {/* LAST NAME */}
                        <div className="input-box">
                            <input type="text" required />
                            <span>Last Name</span>
                        </div>

                        {/* SUBMIT BUTTON */}
                        <button>Thank you!</button>
                    </div>
                </figure>

                {/* TEXT RIGHT COLUMN */}
                <Aside className="col-span-1">
                    <AsideHeader>Fancy Form</AsideHeader>
                    <p>This is a fancy form inspired by MUI form fields.</p>
                    <p>I found this idea on <Link className="link-hover link-hover-slim" target="_blank" href="https://youtu.be/BMphVl9suxA">YouTube</Link>.</p>

                    <AsideFooter>The code can be found in this repository.</AsideFooter>
                </Aside>
            </article>
        </>
    );
};

export default FancyForm;